.\"return the arcsine of a float
.TH asin 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
asin() - return the arcsine of a float

.SH SYNOPSIS
float asin( float f );

.SH DESCRIPTION
Returns the arcsine of its argument, `f', measured in radians.

.SH SEE ALSO
acos(3), atan(3), cos(3), sin(3), tan(3)
