.\"return the cosine of a float
.TH cos 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
cos() - return the cosine of a float

.SH SYNOPSIS
float cos( float f );

.SH DESCRIPTION
Returns the cosine of its argument, `f', measured in radians.

.SH SEE ALSO
acos(3), asin(3), atan(3), sin(3), tan(3)
