.\"returns the natural logarithm of a float
.TH log 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
log() - returns the natural logarithm of a float

.SH SYNOPSIS
float log( float f );

.SH DESCRIPTION
Returns the natural logarithm of its argument, `f'.  `f' must be positive.

.SH SEE ALSO
exp(3), pow(3), sqrt(3)
