.\"returns the square root of a float
.TH sqrt 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
sqrt() - returns the square root of a float

.SH SYNOPSIS
float sqrt( float f );

.SH DESCRIPTION
sqrt() returns the non-negative square root of its argument, `f'.  The value
of `f' must not be negative.

.SH SEE ALSO
exp(3), log(3), pow(3)
