.\"return the tangent of a float
.TH tan 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
tan() - return the tangent of a float

.SH SYNOPSIS
float tan( float f );

.SH DESCRIPTION
Returns the tangent of its argument, `f', measured in radians.

.SH SEE ALSO
acos(3), asin(3), atan(3), cos(3), sin(3)
