OBJ=interface.$(O)
SRC=interface.c

%ifdef GNU
OBJ=$(addprefix $(OBJDIR)/,$(subst .c,.o,$(SRC)))

$(OBJDIR)/%.o: %.c
	$(CC) -I$(OBJDIR) -I.. $(CFLAGS) -o $@ -c $<
%else
.c.$(O):
	$(CC) $(CFLAGS) -I.. -c $*.c
%endif

all: $(OBJ)
	ar rcu mudlib.$(A) $(OBJ)
	$(RANLIB) mudlib.$(A)

clean:
	-rm -f *.$(O)
	-rm -f mudlib.$(A)
