.\"obsolete apply
.TH __INIT 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
__INIT - obsolete apply

.SH SYNOPSIS
__INIT( void );

.SH DESCRIPTION
This function used to be called in objects right before create.
global variable initialization is now handled by another function that
cannot be interfered with, so this is no longer called.
