.\"bind a verb to a local function
.TH add_verb 3

.SH NAME
add_verb() - bind a verb to a local function

.SH SYNOPSIS
void add_verb( string str );

.SH DESCRIPTION
This function is connected to the add_action() function. It will set up
the command <str> to trigger a call to the function set up by the
previous call to add_action().
.PP
This function is now obsolete as the verb can be given directly with
add_action(). add_verb() remains for compatibility.

.SH SEE ALSO
add_action(3), query_verb(3)
