.\"credit an object with additional "worth"
.TH add_worth 3

.SH NAME
add_worth() - credit an object with additional "worth"

.SH SYNOPSIS
void add_worth(int worth, object ob);

.SH DESCRIPTION
add_worth credits an object with having a certain "worth".  This worth
could represent whatever you as the mudlib administrator are
interested in keeping track of, since the end result is that the
objects's domain and author get credited with this object's additional
"worth", which shows up in the domain and author statistics.
.PP
A common use for add_worth is to monitor how much "wealth" is created
in a certain area.  This is to monitor which areas might have too
little or too much "wealth" available in them.

.SH SEE ALSO
author_stats(3), set_author(3), domain_stats(3)
