.\"makes a living object non-living
.TH disable_commands 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
disable_commands() - makes a living object non-living

.SH SYNOPSIS
int disable_commands( void );

.SH DESCRIPTION
Makes a living object non-living, that is, add_actions have no effects,
livingp returns false, and, if the object is interactive, disallows
the user to type in commands other than for an input_to.  disable_commands
always returns 0.

.SH SEE ALSO
enable_commands(3)
