.\"remove wizard privileges from an object
.TH disable_wizard 3

.SH NAME
disable_wizard() - remove wizard priveleges from an object

.SH SYNOPSIS
void disable_wizard();

.SH DESCRIPTION
The opposite of enable_wizard().  Disables wizard privileges from the
current object.

.SH SEE ALSO
enable_wizard(3), wizardp(3)
