.\"give wizard priveleges to an object
.TH enable_wizard 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
enable_wizard() - give wizard priveleges to an object

.SH SYNOPSIS
void enable_wizard( void );

.SH DESRIPTION
Any interactive object that calls enable_wizard() will cause wizardp()
to return true if called on that object.  enable_wizard() gives three
privileges to the interactive object in question:
.TP
1.
ability to use restricted modes of ed when the RESTRICTED_ED option
is compiled into the driver.
.TP
2.
privilege of receiving descriptive runtime error messages.
.TP
3.
privilege of using the trace(3) and traceprefix(3) efuns.

.SH SEE ALSO
disable_wizard(3), wizardp(3)
