.\"return the environment of an object
.TH environment 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
environment() - return the environment of an object

.SH SYNOPSIS
object environment( object ob );

.SH DESCRIPTION
Return the containing object (environment) of <ob>. If no argument
is given, <ob> defaults to this_object().

.SH SEE ALSO
this_object(3)
