.\"return the first item in an object's inventory
.TH first_inventory 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
first_inventory() - return the first item in an object's inventory

.SH SYNOPSIS
object first_inventory( mixed ob );

.SH DESCRIPTION
Return the first object in the inventory of <ob>, where <ob> is
either an object or the file name of an object.

.SH SEE ALSO
file_name(3), next_inventory(3), all_inventory(3), deep_inventory(3)
