.\"query the status of an object's heartbeat
.TH query_heart_beat 3

.SH NAME
query_heart_beat() - query the status of an object's heartbeat

.SH SYNOPSIS
int query_heart_beat();

.SH DESCRIPTION
Returns the value with which set_heart_beat() has been called with on
this object.  If the object has no heartbeat, 0 will be returned.

.SH SEE ALSO
heart_beat(4), set_heart_beat(3)
