.\"unbind a command verb from a local function
.TH remove_action 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
remove_action - unbind a command verb from a local function

.SH SYNOPSIS
int remove_action( string fun, string cmd );

.SH DESCRIPTION
remove_action(3) unbinds a verb cmd from an object function fun. Basically,
remove_action() is the complement to add_action(3) and add_verb(3). When a
verb is no longer required, it can be unbound with remove_action().

.SH RETURN VALUES
remove_action() returns:
.IP
1 on success.
.IP
0 on failure.

.SH SEE ALSO
add_action(3), query_verb(3), init(4)
