.\"set a living name for a living object
.TH set_living_name 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
set_living_name() - set a living name for a living object

.SH SYNOPSIS
void set_living_name( string name );

.SH DESCRIPTION
Set a living name on an object that is living. After this has been done, the
object can be found with "find_living()".

.SH SEE ALSO
enable_commands(3), find_living(3), find_player(3)
