.\"determine whether or not a given variable is a function pointer
.TH functionp 3

.SH NAME
functionp() - determine whether or not a given variable is a function pointer.

.SH SYNOPSIS
int functionp(mixed arg);

.SH DESCRIPTION
Return 1 if `arg' is a function pointer and zero (0) otherwise.  Function
pointers are variables of type 'function' and are constructed as follows:

f = (: obj, func :);

Note that functionp() will return 0 if obj is not either a valid object
pointer or string, and if func is not a string.

.SH SEE ALSO
stringp(3), pointerp(3), objectp(3), lpc/types/function
