.\"determine whether or not a given variable is an object
.TH objectp 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
objectp() - determine whether or not a given variable is an object

.SH SYNOPSIS
int objectp( mixed arg );

.SH DESCRIPTION
Return 1 if `arg' is an object.

.SH SEE ALSO
mapp(3), stringp(3), pointerp(3), intp(3), bufferp(3), floatp(3),
functionp(3), nullp(3), undefinedp(3), errorp(3)
