.\"return the number of references to a data structure
.TH refs 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
refs - return the number of references to a data structure
 
.SH SYNOPSIS
int refs( mixed data );
 
.SH DESCRIPTION
The number of references to `data' will be returned by refs().  This is 
useful for deciding whether or not to make a copy of a data structure
before returning it.

.SH SEE ALSO
children(3), inherit_list(3), deep_inherit_list(3), objects(3)
