.\"return the number of elements in an array or mapping
.TH sizeof 3

.SH NAME
sizeof() - return the number of elements in an array or mapping

.SH SYNOPSIS
int sizeof(mixed var);

.SH DESCRIPTION
Return the number of elements in an array or mapping 'var'.  If `var' is
not an array or a mapping, then '0' is returned.

.SH SEE ALSO
allocate(3).
