.\"convert a float or buffer to an int
.TH to_int 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
to_int - convert a float or buffer to an int
 
.SH SYNOPSIS
int to_int( float | buffer x );
 
.SH DESCRIPTION
If `x' is a float, the to_int() call returns the number of type `int' that is 
equivalent to `x' (with any decimal stripped off).  If `x' is a buffer, the
call returns the integer (in network-byte-order) that is embedded in the
buffer.
 
.SH SEE ALSO
to_float(3), read_buffer(3), sprintf(3), sscanf(3)
