.\"determine whether or not a given object has called enable_wizard().
.TH wizardp 3

.SH NAME
wizardp() - determine whether or not a given object has called enable_wizard().

.SH SYNOPSIS
int wizardp(object arg);

.SH DESCRIPTION
Returns true (1) iff enable_wizard() has been called from the object in
question.

.SH SEE ALSO
userp(3), objectp(3), enable_wizard(3)
