.\"reclaim any lingering objects
.TH reclaim_objects 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
reclaim_objects - reclaim any lingering objets
 
.SH SYNOPSIS
int reclaim_objects( void );
 
.SH DESCRIPTION
Cycles through all objects that are loaded, and frees any lingering objects
that it can.  This could result in a sizable amount of memory being freed up,
depending on how the mud is coded.  Objects are typically left lingering
when a global variable in more than one object contains a pointer to it,
and the object gets destructed.  This efun returns the number of destructed
objects encountered in variables.
 
.SH SEE ALSO
destruct(3)
