.\"return the current system time
.TH time 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
time() - return the number of seconds since January 1, 1970

.SH SYNOPSIS
int time( void );

.SH DESCRIPTION
Return the number of seconds since midnight (GMT) January 1, 1970.

.SH SEE ALSO
ctime(3), localtime(3), time_expression(3), uptime(3)
