.\"read a file into a string
.TH read_file 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
read_file() - read a file into a string

.SH SYNOPSIS
.nf
string read_file( string file, int start_line,
                  int number_of_lines );

.SH DESCRIPTION
Read a line of text from a file into a string.  The second and third
arguments are optional.  If only the first argument is specified, the
entire file is returned (as a string).
.PP
The start_line is the line number of the line you wish to read.  This routine
will return 0 if you try to read past the end of the file, or if you try to
read from a nonpositive line.

.SH SEE ALSO
write_file(3), read_buffer(3)
