.\"appends a string to a file
.TH write_file 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
write_file() - appends a string to a file

.SH SYNOPSIS
int write_file( string file, string str, int flag );

.SH DESCRIPTION
Append the string `str' into the file `file'. Returns 0 or 1 for
failure or success.  If flag is 1, write_file overwrites instead of
appending.

.SH SEE ALSO
read_file(3), write_buffer(3), file_size(3)
