.\"writes a contiguous series of bytes to a file beginning at a given point
.TH write_bytes 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
write_bytes() - writes a contiguous series of bytes to a file

.SH SYNOPSIS
int write_bytes( string path, int start, string series );

.SH DESCRIPTION
This function writes the bytes in 'series' into the file named by 'path'
beginning at byte # 'start'.  It returns zero (0) upon failure, 1 otherwise.

.SH SEE ALSO
write_file(3), read_bytes(3)
