.\"return the lowercase version of a given string
.TH lower_case 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
lower_case() - return the lowercase version of a given string

.SH SYNOPSIS
string lower_case( string str );

.SH DESCRIPTION
Return the lowercase version of a given string (original string remains
unchanged).

.SH SEE ALSO
capitalize(3)
