.\"determine whether or not a given variable is a string
.TH stringp 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
stringp() - determine whether or not a given variable is a string

.SH SYNOPSIS
int stringp( mixed arg );

.SH DESCRIPTION
Return 1 if `arg' is a string.

.SH SEE ALSO
mapp(3), pointerp(3), objectp(3), intp(3), bufferp(3), floatp(3)
functionp(3), nullp(3), undefinedp(3), errorp(3)
