.\"set the uid of another object
.TH export_uid 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
export_uid() - set the uid of another object

.SH SYNOPSIS
int export_uid( object ob );

.SH DESCRIPTION
Set the uid of <ob> to the effective uid of this_object(). It is
only possible when <ob> has an effective uid of 0.

.SH SEE ALSO
this_object(3), seteuid(3), getuid(3),
geteuid(3), previous_object(3), valid_seteuid(4)
