.\"return the user id (uid) of an object
.TH getuid 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
getuid() - return the user id (uid) of an object

.SH SYNOPSIS
string getuid( object ob );

.SH DESCRIPTION
Returns the user id of an object.  The uid of an object is determined at
object creation by the creator_file() function.

.SH SEE ALSO
seteuid(3), geteuid(3), export_uid(3),
this_object(3), previous_object(3), creator_file(4), valid_seteuid(4)
