.\"return the privs string for an object
.TH query_privs 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_privs() - return the privs string for an object

.SH SYNOPSIS
string query_privs( object ob );

.SH DESCRIPTION
Returns the privs string for an object.  The privs string is determined
at compile time via a call to privs_file() in the master object, and changeable
via the set_privs() efun.

This efun is only available if PRIVS is defined at driver compile time.

.SH SEE ALSO
privs_file(4), set_privs(3)
