.\"set the privs string for an object
.TH set_privs 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
set_privs() - set the privs string for an object

.SH SYNOPSIS
void set_privs( object ob, string privs );

.SH DESCRIPTION
Sets the privs string for `ob' to `privs'.

This efun is only available if PRIVS is defined at driver compile time.

.SH SEE ALSO
privs_file(4), query_privs(3)
