.\"determines if a given object had enable_wizard() performed on it
.TH wizardp 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
wizardp() - determines if a given object had enable_wizard() performed in it

.SH SYNOPSIS
int wizardp( object );

.SH DESCRIPTION
Returns 1 if the arg had enable_wizard() performed on it.

.SH SEE ALSO
disable_wizard(3), enable_wizard(3)
