.\"catch incoming snoop text
.TH receive_snoop 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
receive_snoop - catch incoming snoop text

.SH SYNOPSIS
void receive_snoop( string message) ;

.SH DESCRIPTION
If RECEIVE_SNOOP is defined in options.h, whenever a user is snooping another
user, all snoop text is sent to receive_snoop() in his user object.  Inside
of this function, you can do as you wish with the text.  A common activity
would be to receive() it.

.SH SEE ALSO
catch_tell(4), receive(3), receive_message(4)
