.\"displays a message to the current object
.TH receive 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
receive() - displays a message to the current object

.SH SYNOPSIS
int receive( string message );

.SH DESCRIPTION
This efun is an interface to the add_message() function in the driver.
Its purpose is to display a message to the current object.  It returns 1
if the current object is interactive, 0 otherwise.  Often, receive() is
called from within catch_tell(4) or receive_message(4).

.SH SEE ALSO
catch_tell(4), receive_message(4), message(3)
