.\"send a message to an object
.TH tell_object 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
tell_object() - send a message to an object

.SH SYNOPSIS
void tell_object( object ob, string str );

.SH DESCRIPTION
Send a message `str' to object `ob'. If it is an interactive object (a player),
then the message will go to him, otherwise it will go to the local
function "catch_tell()".

.SH SEE ALSO
message(3), write(3), shout(3), say(3), tell_room(3)
