.\"send a message to current player
.TH write 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
write() - send a message to current player

.SH SYNOPSIS
void write( mixed str );

.SH DESCRIPTION
Write a message `str' to current player. `str' can also be a number, which
will be translated to a string.

.SH SEE ALSO
message(3), tell_object(3), tell_room(3), shout(3), say(3)
