#!/usr/bin/env bash
#
# pack-mudlib.sh -- package a mudlib with the WASM FluffOS driver into a
# static web bundle you can serve from any HTTP server.
#
# The output directory contains:
#   fluffos.js / fluffos.wasm   the driver (from a `wasm` preset build)
#   mudlib.js / mudlib.data     your mudlib, packed for the in-memory FS
#   fluffos-boot.js             mount point + config file for the page
#   index.html                  the web terminal (telnet client included)
#
# Usage:
#   tools/wasm/pack-mudlib.sh --mudlib <dir> --config <relative path> \
#       [--driver <dir with fluffos.js/.wasm>] [--mount </name>] [--out <dir>]
#
# Example (package the bundled testsuite):
#   tools/wasm/pack-mudlib.sh --mudlib testsuite --config etc/config.test
#
# Example (your game):
#   tools/wasm/pack-mudlib.sh --mudlib /home/me/mylib --config etc/config \
#       --mount /mylib --out dist/
#
# The config file is read INSIDE the packed image, with the driver chdir'd
# to the mount point -- exactly like running `driver etc/config` natively
# from the mudlib directory. Relative paths in the config keep working.
#
# The script also works from an extracted release zip (where it sits next
# to fluffos.js / fluffos.wasm / index.html): the driver and web shell then
# default to the script's own directory and --out defaults to ./dist.
# Emscripten's file_packager must be reachable (emsdk on PATH).

set -euo pipefail

SELF_DIR=$(cd "$(dirname "$0")" && pwd)

# Two layouts: in the source tree this script lives in tools/wasm/ with the
# driver built under build-wasm/; in the release zip it sits right next to
# fluffos.js / fluffos.wasm / index.html.
if [ -f "$SELF_DIR/fluffos.js" ] && [ -f "$SELF_DIR/index.html" ]; then
  DRIVER_DIR="$SELF_DIR"
  SHELL_HTML="$SELF_DIR/index.html"
  OUT="$PWD/dist"
else
  ROOT=$(cd "$SELF_DIR/../.." && pwd)
  DRIVER_DIR="$ROOT/build-wasm/src"
  SHELL_HTML="$ROOT/src/www/wasm/index.html"
  OUT="$ROOT/build-wasm/dist"
fi

MUDLIB=""
CONFIG=""
MOUNT=""

usage() { grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --mudlib) MUDLIB=$2; shift 2 ;;
    --config) CONFIG=$2; shift 2 ;;
    --driver) DRIVER_DIR=$2; shift 2 ;;
    --mount) MOUNT=$2; shift 2 ;;
    --out) OUT=$2; shift 2 ;;
    *) echo "unknown argument: $1" >&2; usage ;;
  esac
done

[ -n "$MUDLIB" ] && [ -n "$CONFIG" ] || usage
MUDLIB=$(cd "$MUDLIB" && pwd)
[ -z "$MOUNT" ] && MOUNT="/$(basename "$MUDLIB")"

if [ ! -f "$MUDLIB/$CONFIG" ]; then
  echo "error: config file '$CONFIG' not found inside mudlib '$MUDLIB'" >&2
  exit 1
fi
if [ ! -f "$DRIVER_DIR/fluffos.js" ] || [ ! -f "$DRIVER_DIR/fluffos.wasm" ]; then
  echo "error: driver not found in '$DRIVER_DIR' (build the 'wasm' preset first," >&2
  echo "       or pass --driver <dir>)" >&2
  exit 1
fi

# Locate emscripten's file_packager.
FILE_PACKAGER=""
if command -v file_packager >/dev/null; then
  FILE_PACKAGER="file_packager"
else
  EMCC_PATH=$(command -v emcc || true)
  for c in "${EMCC_PATH:+$(dirname "$EMCC_PATH")/tools/file_packager.py}" \
           /usr/share/emscripten/tools/file_packager.py; do
    if [ -n "$c" ] && [ -f "$c" ]; then FILE_PACKAGER="python3 $c"; break; fi
  done
fi
if [ -z "$FILE_PACKAGER" ]; then
  echo "error: emscripten file_packager not found (is emsdk on PATH?)" >&2
  exit 1
fi

mkdir -p "$OUT"

echo "== packing mudlib $MUDLIB -> $MOUNT"
(cd "$(dirname "$MUDLIB")" && \
  $FILE_PACKAGER "$OUT/mudlib.data" \
    --preload "$(basename "$MUDLIB")@$MOUNT" \
    --js-output="$OUT/mudlib.js" >/dev/null)

echo "== boot configuration ($MOUNT, $CONFIG)"
cat > "$OUT/fluffos-boot.js" <<EOF
// Generated by tools/wasm/pack-mudlib.sh -- consumed by index.html.
window.FLUFFOS_BOOT = {
  mount: "$MOUNT",
  config: "$CONFIG",
};
EOF

echo "== driver + web shell"
cp "$DRIVER_DIR/fluffos.js" "$DRIVER_DIR/fluffos.wasm" "$OUT/"
# Prefer an index.html shipped next to a --driver dir (release zips), then
# the layout-derived default.
if [ -f "$DRIVER_DIR/index.html" ]; then
  cp "$DRIVER_DIR/index.html" "$OUT/"
else
  cp "$SHELL_HTML" "$OUT/"
fi

echo
echo "Done: $OUT"
echo "Serve it over HTTP (wasm cannot be loaded from file://), e.g.:"
echo "  python3 -m http.server -d $OUT 8080"
