.\"process telnet suboptions
.TH telnet_suboption 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
telnet_suboption - process telnet suboptions

.SH SYNOPSIS
void telnet_suboption( string buffer );

.SH DESCRIPTION
This apply is called on the interactive object with the parameter given
by the SE telnet suboption, for mudlib defined processing.  For example,
this allows for future support of terminal types.
.PP
The first byte of the buffer is typically a type descriptor,
ie TELOPT_TTYPE. The next byte is a procession option, such
as TELQUAL_IS.  Following this is the type dependent data.
In the case of a terminal type call, the data will be routed
through through the terminal_type() apply instead.
.PP
Possible suboptions:
.IP
.nf
#define TELQUAL_IS    0 // option is...
#define TELQUAL_SEND  1 // send options
#define TELQUAL_INFO  2 // ENVIRON: informational version of IS
#define TELQUAL_REPLY 3 // AUTHENTICATION: client version of IS
#define TELQUAL_NAME  4 // AUTHENTICATION: client version of IS
.fi
