.\"report various driver and mudlib statistics
.TH cache_stats 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
cache_stats() - report various driver and mudlib statistics

.SH SYNOPSIS
void cache_stats( void );

.SH DESCRIPTION
This efun is only available if CACHE_STATS is defined in options.h at
driver build time.  This efun dumps statistics on the call_other() cache
hit rate to the caller's screen.

.SH SEE ALSO
opcprof(3), mud_status(3)
