.\"dump/disassemble an LPC object
.TH dump_prog 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
dump_prog() - dump/disassemble an LPC object

.SH SYNOPSIS
void dump_prog( object ob, int flags default: 0, string file );

.SH DESCRIPTION
dump_prog() dumps information about the program of `obj' to a file,
`file', or "/PROG_DUMP" if `file' is not given.  If the current object
does not have write access to the file, it fails.  

Flags can be a combination of the following values:
1 - include a disassembly of the i-code
2 - include line number information

.SH SEE ALSO
debug_info(3), dumpallobj(3)
