.\"sets the debug level used by the debug() macro in the driver source
.TH set_debug_level 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
set_debug_level() - sets the debug level used by the driver's debug() macro

.SH SYNOPSIS
void set_debug_level( int level );

.SH DESCRIPTION
This efun is only available when the driver is compiled with -DDEBUG_MACRO.
The purpose of this efun is to allow the amount and type of debugging
information produced to be controlled from within the mud (while the
driver is running).
.PP
For more information, read the file debug.h which is included with the
driver source.

.SH SEE ALSO
set_malloc_mask(3)
