.\"sets the mask controlling what malloc debug information the driver displays
.TH set_malloc_mask 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
set_malloc_mask() - sets the mask controlling display of malloc debug info

.SH SYNOPSIS
void set_malloc_mask( int mask );

.SH DESCRIPTION
This efun is only available when DEBUGMALLOC and DEBUGMALLOC_EXTENSIONS are
both defined in options.h at driver build time.  The mask controls what
memory-related debugging information is displayed as the driver allocates
and deallocates memory.  Read md.c in the driver source for more information.

.SH SEE ALSO
debugmalloc(3)
