.\"return the amount of real time that occurred while evaluation an expression
.TH time_expression 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
time_expression() - return the amount of real time that an expression took

.SH SYNOPSIS
int time_expression( mixed expr );

.SH DESCRIPTION
Evaluate <expr>.  The amount of real time that passed during the evaluation
of <expr>, in microseconds, is returned.  The precision of the value is
not necessarily 1 microsecond; in fact, it probably is much less precise.

.SH SEE ALSO
rusage(3), function_profile(3), time(3)
