.\"return the host name
.TH query_host_name 3

.SH NAME
query_host_name() - return the host name

.SH SYNOPSIS
string query_host_name();

.SH DESCRIPTION
query_host_name() returns the name of the host.

.SH RETURN VALUES
query_host_name() returns:
.IP
a string hostname on success.
.IP
an empty string on failure.
