.\"return the host name
.TH query_host_name 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_host_name() - return the host name

.SH SYNOPSIS
string query_host_name( void );

.SH DESCRIPTION
query_host_name() returns the name of the host.

.SH RETURN VALUES
query_host_name() returns:
.IP
a string hostname on success.
.IP
an empty string on failure.

.SH SEE ALSO
resolve(3), socket_address(3), query_ip_name(3), query_ip_number(3)
