.\"return a text description of a socket error
.TH socket_error 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
socket_error() - return a text description of a socket error
.SH SYNOPSIS
.nf
#include <socket_err.h>

string socket_error( int error );

.SH DESCRIPTION
socket_error() returns a string describing the error signified by error.

.SH RETURN VALUES
socket_error() returns:
.IP
a string describing the error on success.
.IP
"socket_error: invalid error number" on bad input.

.SH SEE ALSO
socket_create(3), socket_connect(3)
