.\"return the remote address for an efun socket
.TH socket_address 3

.SH NAME
socket_address() - return the remote address for an efun socket

.SH SYNOPSIS
.nf
#include <socket.h>
#include <socket_errors.h>

string socket_address(int s)

.SH DESCRIPTION
socket_address() returns the remote address for an efun socket s.
The returned address is of the form:
.IP
"127.0.0.1 23".

.SH RETURN VALUES
socket_address() returns:
.IP
a string format address on success.
.IP
an empty string on failure.

.SH SEE ALSO
socket_connect(3), socket_create(3)
