.\"query various driver config settings
.TH get_config 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
get_config() - query various driver config settings

.SH SYNOPSIS
string | int get_config( int );

.SH DESCRIPTION
This efun is used to query the driver's various config
settings.  Please refer to the "runtime_config.h"
include file for a list of currently recognized options.

.SH SEE ALSO
/include/runtime_config.h
