.\"reports information gathered by the getrusage() system call.
.TH rusage 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
rusage() - reports information gathered by the getrusage() system call
 
.SH SYNOPSIS
mapping rusage( void );
 
.SH DESCRIPTION
This efun collects information gathered via the getrusage() system
call.  Read the getrusage() man page for more information on what information
will be collected.  Some systems do not have the getrusage() system call
but do have the times() system call.  On those systems, only "utime"
and "stime" will be available.  Times are reported in milliseconds.
.PP
Here is an example usage of rusage():
.PP
.nf
  void
  create()
  {
      mapping info;
 
      info = rusage();
      write("user time = " + info["utime"] + "ms\\n");
      write("system time = " + info["stime"] + "ms\\n");
  }
.fi
.PP
The available fields are:
.IP
utime, stime, maxrss, ixrss, idrss, isrss, minflt, majflt, nswap, inblock,
oublock, msgsnd, msgrcv, nsignals, nvcsw, nivcsw.
 
.SH SEE ALSO
time_expression(3), function_profile(3), time(3), uptime(3)
