.\"sets the prefix that determines the objects in which tracing will occur.
.TH traceprefix 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
traceprefix() - sets the prefix determining which objects to trace

.SH SYNOPSIS
string traceprefix( string prefix );

.SH DESCRIPTION
If the the traceprefix is set (i.e. not 0) tracing will only occur in objects
having a name with the set prefix.

.SH SEE ALSO
trace(3)
