.\"sets trace flags and returns the old ones.
.TH trace 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
trace() - sets trace flags and returns the old ones.

.SH SYNOPSIS
int trace( int traceflags );

.SH DESCRIPTION
Sets the trace flags and returns the old trace flags.
When tracing is on a lot of information is printed during execution.
.PP
The trace bits are:
.TP 1
Trace all function calls to lfuns.
.TP 2
Trace all calls to "call_other".
.TP 4
Trace all function returns.
.TP 8
Print arguments at function calls and return values.
.TP 16
Print all executed stack machine instructions (produces a lot of output!).
.TP 32
Enable trace in heart beat functions.
.TP 64
Trace calls to apply.
.TP 128
Show object name in tracing.

.SH SEE ALSO
traceprefix(3)
