.\"give a value from a described function call
.TH process_value 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
process_value() - give a value from a described function call
 
.SH SYNOPSIS
mixed process_value( string calldescription );
 
.SH DESCRIPTION
Get the replacement of one syntactic pattern. The pattern is on
the form:
.IP
   "function[:filename][|arg1|arg2....|argN]"
.PP
The returned value can be of any type.
.PP
Note that both object and arguments are marked optional with the
brackets and that the brackets are not included in the actual pattern.
 
.SH SEE ALSO
process_string(3)
 
.SH CAVEAT
This is usually used to support 'value by function call' in the mudlib.
It is wise to set the effuserid of the object to 0 before using
process_value as any function in any object can be called with almost
any arguments.
