.TH telnet-client 1 LIBTELNET "" "TELNET Library"

.SH NAME
telnet-client \- simplistic TELNET client

.SH SYNOPSIS
\fBtelnet-client\fR <\fBremote address\fR> <\fBremote port\fR>

.SH DESCRIPTION
\fBtelnet-client\fR is an extremely simplistic TELNET client, designed solely as a test of libtelnet functionality and for testing simple TELNET servers or proxies.

\fBtelnet-client\fR should not be used for real work.

.SH SEE ALSO
\fBtelnet-chatd\fR(1), \fBtelnet-proxy\fR(1), \fBtelnet\fR(1)
