.\"return an array of all living objects
.TH livings 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
livings() - return an array of all living objects

.SH SYNOPSIS
object *livings( void );

.SH DESCRIPTION
Returns an array of pointers to all living objects (objects that have
had enable_commands() called in them).

.SH SEE ALSO
enable_commands(3), find_living(3), users(3), objects(3)
