.\"function in master that is called when the driver crashes.
.TH crash 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
crash - function in master that is called in the event the driver crashes

.SH SYNOPSIS
.nf
void crash( string crash_message, object command_giver,
            object current_object );

.SH DESCRIPTION
The driver calls crash() in master in the event that the driver crashes
(segmentation fault, bus error, etc).  This function offers a way to
shutdown the mudlib (safe players and other important data) before the driver
crashes.  It also lets you log various useful information such as what
signal crashed the driver, what object was active, who the current player
was etc.

.SH SEE ALSO
slow_shutdown(4), shutdown(3)
