.\"handle mudlib specific flags specified at driver startup
.TH flag 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
flag - handle mudlib specific flags specified at driver startup

.SH SYNOPSIS
void flag( string );

.SH DESCRIPTION
This master apply is called for each command line
option passed to the driver with the -f flag.
