.\"specifies the privs string to give to a newly created object
.TH privs_file 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
privs_file - specifies the privs string to give to a newly created object

.SH SYNOPSIS
string privs_file( string filename );

.SH DESCRIPTION
The privs_file() function is called in the master object when a new file
is created.  The `filename' of the object is passed as the argument, and
the string that privs_file() returns is used as the new object's privs
string.

The privs_file() functionality is only available if the driver is compiled
with the PRIVS option defined.

.SH SEE ALSO
query_privs(3), set_privs(3)
