.\"controls the use of link(3)
.TH valid_link 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
valid_link - controls the use of link(3)

.SH SYNOPSIS
int valid_link( string from, string to );

.SH DESCRIPTION
The driver calls valid_link(from, to) in the master object from inside the
link(from, to) efunction.  If valid_link() returns 0, then the link()
will fail.  If valid_link() returns 1, then the link(3) will succeed if
rename() would succeed if called with the same arguments.

.SH SEE ALSO
link(3)
