.\"determine whether or not a given variable is a mapping
.TH mapp 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
mapp() - determine whether or not a given variable is a mapping

.SH SYNOPSIS
int mapp( mixed arg );

.SH DESCRIPTION
Return 1 if `arg' is a mapping.

.SH SEE ALSO
stringp(3), pointerp(3), objectp(3), intp(3), bufferp(3), floatp(3)
functionp(3), nullp(3), undefinedp(3), errorp(3)
