.\"return the arccosine of a float
.TH acos 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
acos() - return the arccosine of a float

.SH SYNOPSIS
float acos( float f );

.SH DESCRIPTION
Returns the arccosine of its argument, `f', measured in radians.

.SH SEE ALSO
asin(3), atan(3), cos(3), sin(3), tan(3)
