.\"return the arctangent of a float
.TH atan 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
atan() - return the tangent of a float

.SH SYNOPSIS
float atan( float f );

.SH DESCRIPTION
Returns the arctangent of its argument, `f', measured in radians.

.SH SEE ALSO
acos(3), asin(3), cos(3), sin(3), tan(3)
