.\"round a float up to the nearest integer
.TH ceil 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
ceil() - round a float up to the nearest integer

.SH SYNOPSIS
float ceil( float f );

.SH DESCRIPTION
Returns (as a float) the nearest integer number equal to or greater than f.

.SH SEE ALSO
floor(3), to_int(3), to_float(3)
