.\"round a float down to the nearest integer
.TH floor 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
floor() - round a float down to the nearest integer

.SH SYNOPSIS
float floor( float f );

.SH DESCRIPTION
Returns (as a float) the nearest integer number equal to or smaller than f.

.SH SEE ALSO
ceil(3), to_int(3), to_float(3)
