.\"commits the last transaction
.TH db_commit 3 "24 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
db_commit() - commits the last transaction

.SH SYNOPSIS
int db_commit(int handle );

.SH DESCRIPTION
For transactional databases this will commit the last set of actions.

Returns 1 on success, 0 otherwise

.SH NOTES
Not yet implemented!

.SH SEE ALSO
db_exec(3), db_rollback(3), valid_database(4)
