.\"close the database connection
.TH db_close 3 "23 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
db_close() - close the database connection

.SH SYNOPSIS
int db_close( int handle );

.SH DESCRIPTION
Closes the database connection represented by the given handle.

Returns 1 on success, 0 otherwise

.SH SEE ALSO
db_connect(3), db_status(3), valid_database(4)
