.\"executes an sql statement
.TH db_exec 3 "24 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
db_exec() - executes an sql statement

.SH SYNOPSIS
mixed db_exec( int handle, string sql_query );

.SH DESCRIPTION
This function will execute the passed sql statement for the given database
handle.

Returns the number of rows in result set on success, an error string
otherwise.

.SH SEE ALSO
db_commit(), db_fetch(3), db_rollback(3), valid_database(4)
