.\"undo the last transaction
.TH db_rollback 3 "24 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
db_rollback() - rollback the last transaction

.SH SYNOPSIS
int db_rollback( int );

.SH DESCRIPTION
For transactional databases this will rollback the last set of actions.

Returns 1 on success, 0 otherwise

.SH NOTES
Not yet implemented!

.SH SEE ALSO
db_commit(3), db_exec(3), valid_database(4)
