.\"return package status
.TH db_close 3 "23 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
db_status() - return package status

.SH SYNOPSIS
string db_status( void );

.SH DESCRIPTION
Returns a string describing the current status of the database package.

.SH SEE ALSO
db_close(3), db_connect(3), valid_database(4)
