int remove_shadow(object);
mixed query_notify_fail();
void set_prompt(string, void|object);
mixed copy(mixed);
string *functions(object);
string terminal_colour(string, mapping);
string pluralize(string);
int file_length(string);
string upper_case(string);
int replaceable(object);
void program_info();
void store_variable(string, mixed);
mixed fetch_variable(string);