.\"modify an array
.TH map_array 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
map_array() - modify an array of elements via application of a function

.SH SYNOPSIS
.nf
mixed *map_array( mixed *arr, string fun, object ob,
                  mixed extra, ... );
mixed *map_array( mixed *arr, function f, mixed extra, ... );

.SH DESCRIPTION
Returns an array holding the items of `arr' mapped through either 
`ob->fun()' or 'f'.  The function is called for each element in 'arr'
with that element as a parameter. A second parameter `extra' is sent
in each call if given.
Principal function: 
.IP
.nf
foreach (index) arr[index] = ob->fun(arr[index],extra);
.PP
The value returned by `ob->fun(arr[.index.], extra)' replaces the existing 
element in the array. If `arr' is not an array, then 0 will be returned.

.SH SEE ALSO
filter_array(3), sort_array(3), map(3)
