.\"returns the index of the first occurence of a given item in an array
.TH member_array 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
member_array() - returns index first occurence of a given item in an array

.SH SYNOPSIS
int member_array( mixed item, mixed *arr, int flag );

.SH DESCRIPTION
Returns the index of the first occurence of `item' in array `arr'.
If the item is not found, then -1 is returned.  If `flag' is 1 and `item'
is a string, then only the first `strlen(item)' characters of each element
of `arr' are compared against `item'.
