.\"returns the index of the first occurence of a given item in an array
.TH member_array 3

.SH NAME
member_array() - returns index first occurence of a given item in an array

.SH SYNOPSIS
int member_array(mixed item, mixed *arr);

.SH DESCRIPTION
Returns the index of the first occurence of `item' in array `arr'.
If the item is not found, then -1 is returned.
