.\"returns the index of an occurence of a given item in an array or string
.TH member_array 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
member_array() - returns index of an occurence of a given item in an
array or string

.SH SYNOPSIS
int member_array( mixed item, mixed * | string arr, void | int start );

.SH DESCRIPTION
Returns the index of the first occurence of `item' in array `arr', or
the first occurence at or after 'start'.
If the item is not found, then -1 is returned.
