.\"restore values of a variable from a string
.TH restore_variable 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
restore_variable() - restore value of a variable from a string
 
.SH SYNOPSIS
mixed restore_variable( string value );
 
.SH DESCRIPTION
Restore values of a variable from a string.  The format used is the
same format as save/restore_object.
 
.SH SEE ALSO
restore_object(3)
