.\"save the value of a variables into a string
.TH save_variable 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
save_variable() - save the value of variable into a string

.SH SYNOPSIS
string save_variable( mixed var );

.SH DESCRIPTION
Saves the value of a variable to a string.  The format is the same as
save/restore_object.

.SH SEE ALSO
save_object(3)
