.\"zero a bit in a bitstring
.TH clear_bit 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
clear_bit() - zero a bit in a bit string

.SH SYNOPSIS
string clear_bit( string str, int n );

.SH DESCRIPTION
Return the new string where bit <n> is cleared in string <str>. Note that
the old string <str> is not modified.

.SH SEE ALSO
set_bit(3), test_bit(3)
