.\"compute the cyclic redundacy code for a buffer or string
.TH crc32 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
crc32() - compute the cycle redundancy code for a buffer or string

.SH SYNOPSIS
int crc32( buffer | string x );

.SH DESCRIPTION
Computes and returns the CRC-32 code for the given buffer or string, `x'.
