.\"break up a string
.TH explode 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
explode() - break up a string

.SH SYNOPSIS
string *explode( string str, string del );

.SH DESCRIPTION
explode() returns an array of strings, created when the string <str>
is split into pieces as divided by the delimiter <del>.

.SH EXAMPLE
explode(str," ") will return as an array all of the words (separated
by spaces) in the string <str>.

.SH SEE ALSO
sscanf(3), extract(3), replace_string(3), strsrch(3)
