.\"set a bit in a bitstring
.TH set_bit 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
set_bit() - set a bit in a bitstring

.SH SYNOPSIS
string set_bit( string str, int n );

.SH DESCRIPTION
Return the new string where bit `n' is set in string `str'. Note that
the old string `str' is not modified.
.PP
The max value of `n' is limited. Ask the administrator if you want to
now the maximum value.
.PP
The new string will automatically be extended if needed.
.PP
Bits are packed 6 per byte in printable strings.

.SH SEE ALSO
clear_bit(3), test_bit(3)
