.\"returns the length of a string
.TH strlen 3

.SH NAME
strlen() - returns the length of a string

.SH SYNOPSIS
int strlen( string str );

.SH DESCRIPTION
strlen returns the length of the string <str>.  The length of a string
is defined as the number of characters appearing before the first
character 0 ('\\0').
