.\"search for substrings in a string
.TH strsrch 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
strsrch() - search for substrings in a string
 
.SH SYNOPSIS
.nf
int strsrch( string str, string substr | int char,
             int flag );
 
.SH DESCRIPTION
strsrch() searches for the first occurance of the string `substr' in the 
string `str'.  The last occurance of `substr' can be found by passing `-1' 
as the 3rd argument (which is optional).  If the second argument is an 
integer, that character is found (a la C's strchr()/strrchr().)  The empty 
string or null value cannot be searched for.
 
.SH RETURN VALUE
The integer offset of the first (last) match is returned.  -1 is returned
if there was no match, or an error occurred (bad args, etc).
 
.SH SEE ALSO
explode(3), sscanf(3), replace_string(3), regexp(3)
