.\"periodically called in inactive objects
.TH clean_up 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
clean_up - periodically called in inactive objects

.SH SYNOPSIS
int clean_up( int inherited );

.SH DESCRIPTION
The clean_up() function is called by the driver on a regular basis in all
objects that have been inactive for the time specified for clean_up() in the
runtime configuration file.  One flag is passed to the function, specifying
whether or not the object has been inheritted by anything.  If clean_up()
returns 0, clean_up() will never be called again on that object.  If it returns
1, it will be called again when the object remains inactive for the specified
clean_up() delay.
.PP
One thing that might be commonly done by an object in this function is
destructing itself to conserve memory.
