.\"object initialization
.TH create 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
create - object initialization

.SH SYNOPSIS
void create( void );

.SH DESCRIPTION
Every object should have a create function defined within it.  Within
that function, all initial object initialization should be done.
create() is called on *all* objects.  *NOTE* - This behavior is
different than the stock 3.1.2 LPmud driver.  In 3.1.2, if an object
is created first by being inherited, then create() wasn't called on
it.  In MudOS, this behavior has changed so that it is *always* called
when an object is created.  As a result, you may see some odd behavior
if you have a create in a parent object that does a write, you will
see two writes, as if create() had been called twice on the same
object.  In reality, create *is* being called twice, but on two
*different* objects: the parent, and the child that is calling
parent::create() manually.

.SH SEE ALSO
reset(4), __INIT(4)

.SH AUTHOR
Wayfarer@Portals
