.\"allows master to relocate object when environment is destructed
.TH destruct_env_of 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
destruct_env_of - allows master to relocate object when environment is destructed

.SH SYNOPSIS
void destruct_env_of( object );

.SH DESCRIPTION
This master apply is called by destruct() on each of
the destructed object's contents, when the
destructed object has no environment (eg a room).
It allows the mud to specify what to do with the destructed
object's contents (eg players) or inventory.

.SH NOTE
This master apply used to be named destruct_environment_of().

.SH SEE ALSO
destruct(3), move(4)
