.\"determine the domain for a given object
.TH domain_file 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
domain_file - determine the domain for a given object

.SH SYNOPSIS
string domain_file( string file );

.SH DESCRIPTION
This function must exist in the master object.  It is called by the
domain statistic functions in the driver to determine what domain a
given object should be associated with.  This is totally arbitrary and
up to the mudlib designers wishes.  It should be noted that the domain
that the object is assigned to will receive "credit" for all of the
objects behavior (errors, heart_beats, worth, etc).

.SH SEE ALSO
author_stats(3), domain_stats(3), author_file(4)

.SH AUTHOR
Wayfarer@Portals
