.\"function in an object called by move_object() to initialize verb/actions
.TH init 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
init - function in an object called by move_object() to initialize verb/actions

.SH SYNOPSIS
void init( void );

.SH DESCRIPTION
When the mudlib moves an object "A" inside another object "B", the
driver (the move_object() efunction) does the following:
.TP
1.
if "A" is living, causes "A" to call the init() in "B"
.TP
2.
causes each living object in the inventory of "B" to call init() in
"A".  regardless of whether "A" is living or not.
.TP
3.
if "A" is living, causes "A" to call the init() in each object in
the inventory of "B".
.PP
Note: an object is considered to be living if enable_commands(3) has
been called by that object.
.PP
Typically, the init(4) function in an object is used to call add_action(3)
for each command that the object offers.

.SH SEE ALSO
reset(4), move_object(3), enable_commands(3), living(3), add_action(3)
