.\"log errors intelligently
.TH log_error 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
log_error - log errors intelligently

.SH SYNOPSIS
void log_error( string file, string message );

.SH DESCRIPTION
Whenever an error occurs during compilation, the function log_error in
the master object is called with the filename that the error occurred
in and the error message itself.  Then, log_error is free to do
whatever it thinks it should do with that information.  Usually this
is deciding based on the filename where the error message should be
logged, and then writing it to that file.

.SH SEE ALSO
error_handler(4)

.SH AUTHOR
Wayfarer@Portals
