.\"attach an object to a login connection
.TH logon 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
logon - attach an object to a login connection

.SH SYNOPSIS
object logon( void );

.SH DESCRIPTION
This master apply is called by the driver each time
a new connection is received at the mud port.  The
function should return a login/connection/player object.
The input_to() efun can't be called here.

.SH SEE ALSO
connect(4)
