.\"called by the MudOS driver to find out an interactive object's name
.TH QUERY_NAME 4

.SH NAME
query_name \- called by the MudOS driver to find out an interactive object's name

.SH SYNOPSIS
string query_name()

.SH DESCRIPTION
This function is called by the driver when LOG_SHOUTS was defined as a
compile-time option.  With that option, every call to the efun shout()
is logged to a file.  If the object doing the shout is a user, then
the name of the user is determined for the purposes of the log by
calling query_name() on that object.
