.\"controls which objects can be shadowed
.TH valid_shadow 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
valid_shadow - controls which objects can be shadowed

.SH SYNOPSIS
int valid_shadow( object ob );

.SH DESCRIPTION
When an object attempts to shadow `ob' (with the shadow() efun), valid_shadow
in the master object is called.  One object parameter is passed, which is the
object that previous_object() is attempting to shadow.  valid_shadow() should
return 0 if the shadow should not be permitted, in which case the shadow() call
will return 0 and fail.  If valid_shadow() returns 1, the shadow is allowed.

.SH SEE ALSO
shadow(3), query_shadowing(3)
