.\"copy a file
.TH cp 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
cp() - copy a file
 
.SH SYNOPSIS
int cp( string src, string dst );
 
.SH DESCRIPTION
Copies the file <src> to the file <dst>.
 
.SH RETURN VALUE
Returns 1 for success, returns a negative value in case of failure.
 
.SH SEE ALSO
rm(3), rmdir(3), rename(3), link(3)
