.\"link a file to another
.TH link 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
link() - link a file to another

.SH SYNOPSIS
void link( string original, string reference );

.SH DESCRIPTION
Creates a link <reference> to the file <original>.  This efun causes
valid_link(original, reference) to be called in the master object.  If
valid_link() returns 0, the link() call fails.  If valid_link() returns 1
then the link() suceeds iff rename() would succeed if called with the same
arguments.

Note: This efun creates a hard link, not a symbolic one.

.SH SEE ALSO
rm(3), rmdir(3), rename(3), mkdir(3), cp(3)
