.\"append a message to a log file
.TH log_file 3

.SH NAME
log_file() - append a message to a log file

.SH SYNOPSIS
void log_file(string file, string message);

.SH DESCRIPTION
Append a message to a log file.  The log directory is to be specified
in the runtime configuration file.  The log directory is automatically
prepended to the filename.

.SH SEE ALSO
write_file(3), write_bytes(3).
