.\"reads a contiguous series of bytes from a file into a string
.TH read_bytes 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
read_bytes() - reads a contiguous series of bytes from a file into a string

.SH SYNOPSIS
string read_bytes( string path, int start, int length );

.SH DESCRIPTION
This function reads 'length' bytes beginning at byte # 'start' in the
file named 'path'.  The bytes are returned as a string.  Note that
(start + length) must not be past the end of the file or else read_bytes
will fail.  If the second and third arguments are omitted, the entire file
is returned.

.SH SEE ALSO
read_file(3), write_bytes(3)
