.\"rename a file
.TH rename 3

.SH NAME
rename() - rename a file

.SH SYNOPSIS
int rename(string src, string dst);

.SH DESCRIPTION
Renames the file <src> to <dst>.

.SH RETURN VALUE
rename() returns zero (0) to indicate success.  Nonzero indicates failure.

.SH SEE ALSO
rm(3), rmdir(3), cat(3), cp(3).
