.\"restore values of variables from a file into an object
.TH restore_object 3

.SH NAME
restore_object() - restore values of variables from a file into an object

.SH SYNOPSIS
int restore_object(string name)

.SH DESCRIPTION
Restore values of variables for current object from file `name'.
It is illegal to have '.' or spaces in the name.
Return true if success.
.PP
Variables that has the type modifer `static' will not be saved.
Example: `static int xxx;'.

.SH SEE ALSO
save_object(3).
