.\"remove a directory
.TH rmdir 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
rmdir() - remove a directory
 
.SH SYNOPSIS
int rmdir( string dir );
 
.SH DESCRIPTION
Remove directory `dir'.
 
.SH RETURN VALUE
Returns nonzero for success, zero (0) for failure.
 
.SH SEE ALSO
rm(3), mkdir(3), link(3)
