.\"displays the latter portion of a file
.TH tail 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
tail() - displays the latter portion of a file

.SH SYNOPSIS
int tail( string path );

.SH DESCRIPTION
This efunction displays the latter portion of the file named by path.
It returns 1 if successful, 0 otherwise (e.g. when the file is protected
against reading).

.SH SEE ALSO
read_file(3), read_buffer(3), file_size(3)
