.\"log debug message
.TH debug_message 3 "30 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
debug_message() - logs a debug mssage

.SH SYNOPSIS
void debug_message(string msg);

.SH DESCRIPTION
Prints the given message on the <stderr> file desciptor of the driver and
appends it to the debug log.
