.\"search for the maximum in an array
.TH max 3 "30 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
max() - searches for the maximum value inside an array

.SH SYNOPSIS
mixed max(mixed * arr)
mixed max(mixed * arr, int flag);

.SH DESCRIPTION
Searches maximum value for (int|float|string) arrays.
If flag is 0 or omitted the maximum value will be returned, otherwise the
first index of its occurrence.

.SH SEE ALSO
min(3)
