.\"search for the minimum in an array
.TH min 3 "30 Dec 2015" FluffOS "LPC Library Functions"

.SH NAME
min() - searches for the minimum value inside an array

.SH SYNOPSIS
mixed min(mixed * arr)
mixed min(mixed * arr, int flag);

.SH DESCRIPTION
Searches minimum value for (int|float|string) arrays.
If flag is 0 or omitted the minimum value will be returned, otherwise the
first index of its occurrence.

.SH SEE ALSO
max(3)
