.\"convert an int to a float
.TH to_float 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
to_float - convert an int to a float
 
.SH SYNOPSIS
float to_float( int i );
 
.SH DESCRIPTION
The to_float() call returns the number of type `float' that is equivalent to
the int `i'.
 
.SH SEE ALSO
to_int(3), read_buffer(3), sprintf(3), sscanf(3)
