.\"remove an object from the game
.TH destruct 3

.SH NAME
destruct() - remove an object from the games

.SH SYNOPSIS
void destruct(object ob);

.SH DESCRIPTION
Completely destroy and remove object `ob'. After the call to destruct(), no 
global variables will exist any longer, only local, and arguments.  If
`ob' is this_object(), execution will continue, but it is best to return
a value immediately.

.SH SEE ALSO
clone_object(3)
