.\"find an object by file name
.TH find_object 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
find_object() - find an object by file name

.SH SYNOPSIS
object find_object( string str );

.SH DESCRIPTION
Find the object with the file name <str>.  If the object is a
cloned object, then it can be found using the file name which
would by returned if file_name() was called with it as the
argument.

.SH SEE ALSO
file_name(3), stat(3)
