.\"finds which file defines a given function in a given object
.TH function_exists 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
function_exists() - find the file containing a given function in an object 

.SH SYNOPSYS
string function_exists( string str, object ob );

.SH DESCRIPTION
Return the file name of the object that defines the function `str' in
object `ob'. The returned value can be other than `file_name(ob)' if the
function is defined by an inherited object.
.PP
0 is returned if the function was not defined.
.PP
Note that function_exists() does not check shadows.

.SH SEE ALSO
call_other(3), call_out(3), functionp(3), valid_shadow(4)
