.\"determine if an object inherits a given file
.TH inherits 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
inherits() - determine if an object inherits a given file

.SH SYNOPSIS
int inherits( string file, object obj );

.SH DESCRIPTION
inherits() returns 0 if obj does not inherit file, 1 if it inherits the
most recent copy of file, and 2 if it inherits an old copy of file.

.SH SEE ALSO
deep_inherit_list(3), inherit_list(3)
