.\"get a list of parents of an object
.TH inherit_list 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
inherit_list() - get a list of parents of an object

.SH SYNOPSIS
string *inherit_list( object obj );

.SH DESCRIPTION
Returns an array of filenames of objects inherited by obj.  Only directly
inherited files are returned.  E.g. if A inherits B which inherits C,
inherit_list(A) will return an array with B, but not C.

.SH SEE ALSO
deep_inherit_list(3), inherits(3)
