.\"return an array of all loaded objects
.TH objects 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
objects - return an array of all loaded objects
 
.SH SYNOPSIS
object *objects( string func, object ob );
object *objects( function f);
 
.SH DESCRIPTION
An array of every object loaded on the mud is returned by objects().  Note
that if the system's maximum array size is set too low, objects() will
truncate its array, in which case it might not be too useful.
.PP
If the optional `func' and `ob' parameters are given, then ob->func()
is called with each loaded object as an argument.  If the function returns
nonzero, then that object is returned by objects(), otherwise it isn't.
.PP
If 'f' is given, it will be called on all the objects as above.  For
example, objects( (: clonep :) ) returns a list of all the clones in
existence.

.SH SEE ALSO
livings(3), users(3)
