.\"find an object with a given id in a given environment
.TH present 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
present() - find an object by id

.SH SYNOPSIS
object present( mixed str, object ob );

.SH DESCRIPTION
If an object that identifies to the name `str' is present,
then return it.
.PP
`str' can also be an object, in which case the test is much faster and easier.
.PP
If `ob' is given, then the search is done in the inventory of `ob', otherwise
the object is searched for in the inventory of the current object, and
in the inventory of the environment of the current object.

.SH SEE ALSO
move_object(3), environment(3)
