.\"find an object with a given id in a given environment
.TH present() 3

.SH NAME
present() - find an object by id

.SH SYNOPSIS
object present(mixed str, object ob)

.SH DESCRIPTION
If an object that identifies to the name `str' is present,
then return it.
.PP
`str' can also be an object, in which case the test is much faster and easier.
.PP
The object is searched for in the inventory of the current object, and
in the inventory of the environment of the current object.
.PP
A second optional argument `ob' is the enviroment where the search for the
`str' is done. Normally "this_player()" is a good environment.

.SH SEE ALSO
move_object(3), environment(3).
