.\"query the status of an object's heartbeat
.TH query_heart_beat 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_heart_beat() - query the status of an object's heartbeat

.SH SYNOPSIS
int query_heart_beat( object );

.SH DESCRIPTION
Returns the value with which set_heart_beat() has been called with on
`object'.  If object is not given, it defaults to the current object.  If
the object has no heart beat, 0 will be returned.

.SH SEE ALSO
heart_beat(4), set_heart_beat(3)
