.\"returns the machine/OS type that the driver is running on
.TH arch 3
.SH NAME
arch() - returns the machine/OS type that the driver is running on

.SH SYNOPSIS
string arch();

.SH DESCRIPTION
Returns a string containing the name of the machine/OS that the driver
is running on, or "unknown" if it was not determinable at compile-time.

.SH SEE ALSO
mud_name(3), version(3)
