.\"returns the mud name as defined in the config file
.TH mud_name 3

.SH NAME
mud_name() - returns the mud name as defined in the config file

.SH SYNOPSIS
string mud_name();

.SH DESCRIPTION
Returns a string containing the name of the mud as defined in
the configuration file the driver used on startup.

.SH SEE ALSO
arch(3), version(3)
