.\"report statistics on the frequency with which efuns have been called.
.TH opcprof 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
opcprof() - reports statistics on calling frequencies of various efuns

.SH SYNOPSIS
void opcprof( string | void );

.SH DESCRIPTION
This function dumps a list of statistics on each efunction and eoperator.
If no argument is specified, then the information will be dumped to files
named /OPCPROF.efun and /OPCPROF.eoper.  If an argument is specified, then
that name is used as the filename for the dump.

.SH SEE ALSO
function_profile(3)
