.\"return the name of the current command
.TH query_verb 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_verb() - return the name of the command currently being executed

.SH SYNOPSIS
string query_verb( void );

.SH DESCRIPTION
Give the name of the current command, or 0 if not executing from a command.
This function is useful when several commands (verbs) may cause the same
function to execute and it is necessary to determine which verb it was
that invoked the function.

.SH SEE ALSO
add_action(3)
