.\"return the object pointer of the calling object
.TH this_object 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
this_object() - return the object pointer of the calling object

.SH SYNOPSIS
object this_object( void );

.SH DESCRIPTION
Return the object pointer of this object.  This function is useful when
an object wants to call functions that are not in the same source file but
are in the same object (via inheritance).

.SH SEE ALSO
this_player(3), previous_object(3), origin(3)
