.\"return the object representing the current player
.TH this_player 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH SYNOPSIS
object this_player( int flag );

.SH DESCRIPTION
Return the object representing the player that caused the calling function
to be called.  Note that this_player() may return a different value than
this_object() even when called from within a player object.  If this_player
is called as this_player(1) then the returned value will be the interactive
that caused the calling function to be called.  this_player(1) may return
a different value than this_player() in certain cases (such as when command()
is used by an admin to force a player to perform some command).

.SH SEE ALSO
this_object(3)
