.\"determine whether or not a given variable is a buffer
.TH bufferp 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
bufferp() - determine whether or not a given variable is a buffer

.SH SYNOPSIS
int bufferp( mixed arg );

.SH DESCRIPTION
Return 1 if `arg' is a buffer value and zero (0) otherwise.

.SH SEE ALSO
mapp(3), stringp(3), pointerp(3), objectp(3), intp(3), bufferp(3), floatp(3),
functionp(3), nullp(3), undefinedp(3), errorp(3)
