encoding: UTF-8
timezone: America/Los_Angles
url: https://www.fluffos.info

plugins:
  - jekyll-seo-tag                  # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap                  # https://github.com/jekyll/jekyll-sitemap/
