/* autogenerated from 'applies' */
#ifndef APPLIES_H
#define APPLIES_H

extern const char *applies_table[];

/* the folowing must be the first character of __INIT */
#define APPLY___INIT_SPECIAL_CHAR		'#'
#define APPLY___INIT                        	"#global_init#"
#define APPLY_ADJECTIVE                     	"parse_command_adjectiv_id_list"
#define APPLY_CATCH_TELL                    	"catch_tell"
#define APPLY_CLEAN_UP                      	"clean_up"
#define APPLY_CREATE                        	"create"
#define APPLY_DESTRUCTOR                    	"destructor"
#define APPLY_ID                            	"id"
#define APPLY_INIT                          	"init"
#define APPLY_LOGON                         	"logon"
#define APPLY_MOVE                          	"move_or_destruct"
#define APPLY_NET_DEAD                      	"net_dead"
#define APPLY_NOUN                          	"parse_command_id_list"
#define APPLY_PLURAL                        	"parse_command_plural_id_list"
#define APPLY_PROCESS_INPUT                 	"process_input"
#define APPLY_QGET_ADJID                    	"parse_command_adjective_id_list"
#define APPLY_QGET_ID                       	"parse_command_id_list"
#define APPLY_QGET_PLURID                   	"parse_command_plural_id_list"
#define APPLY_RECEIVE_MESSAGE               	"receive_message"
#define APPLY_RECEIVE_SNOOP                 	"receive_snoop"
#define APPLY_RECEIVE_ED                    	"receive_ed"
#define APPLY_RESET                         	"reset"
#define APPLY_TELNET_SUBOPTION              	"telnet_suboption"
#define APPLY_TERMINAL_TYPE                 	"terminal_type"
#define APPLY_TERMINAL_COLOUR_REPLACE       	"terminal_colour_replace"
#define APPLY_WINDOW_SIZE                   	"window_size"
#define APPLY_WRITE_PROMPT                  	"write_prompt"
#define APPLY_MXP_ENABLE                    	"mxp_enable"
#define APPLY_MXP_TAG                       	"mxp_tag"
#define APPLY_ZMP                           	"zmp_command"
#define APPLY_GMCP_ENABLE                   	"gmcp_enable"
#define APPLY_GMCP                          	"gmcp"
#define APPLY_RECEIVE_ENVIRON               	"receive_environ"
#define APPLY_AUTHOR_FILE                   	0
#define APPLY_COMPILE_OBJECT                	1
#define APPLY_CONNECT                       	2
#define APPLY_CRASH                         	3
#define APPLY_CREATOR_FILE                  	4
#define APPLY_DOMAIN_FILE                   	5
#define APPLY_EPILOG                        	6
#define APPLY_ERROR_HANDLER                 	7
#define APPLY_GET_BACKBONE_UID              	8
#define APPLY_GET_ED_BUFFER_SAVE_FILE_NAME  	9
#define APPLY_GET_ROOT_UID                  	10
#define APPLY_LOG_ERROR                     	11
#define APPLY_MAKE_PATH_ABSOLUTE            	12
#define APPLY_FLAG                          	13
#define APPLY_OBJECT_NAME                   	14
#define APPLY_PARSER_ERROR_MESSAGE          	15
#define APPLY_PRELOAD                       	16
#define APPLY_PRIVS_FILE                    	17
#define APPLY_RETRIEVE_ED_SETUP             	18
#define APPLY_SAVE_ED_SETUP                 	19
#define APPLY_SLOW_SHUTDOWN                 	20
#define APPLY_USERS                         	21
#define APPLY_VALID_ASM                     	22
#define APPLY_VALID_BIND                    	23
#define APPLY_VALID_DATABASE                	24
#define APPLY_VALID_HIDE                    	25
#define APPLY_VALID_LINK                    	26
#define APPLY_LITERALS                      	27
#define APPLY_VALID_OBJECT                  	28
#define APPLY_VALID_OVERRIDE                	29
#define APPLY_QGET_ALLWORD                  	30
#define APPLY_QGET_PREPOS                   	31
#define APPLY_VALID_READ                    	32
#define APPLY_VALID_SETEUID                 	33
#define APPLY_VALID_SHADOW                  	34
#define APPLY_VALID_SOCKET                  	35
#define APPLY_VALID_WRITE                   	36
#define APPLY_PARSE_FIRST_INVENTORY         	37
#define APPLY_PARSE_NEXT_INVENTORY          	38
#define APPLY_PARSE_ENVIRONMENT             	39
#define APPLY_GET_MUD_STATS                 	40

#define NUM_MASTER_APPLIES	41

#endif
