/* this file automatically generated by the Makefile */
#define COMPILER "g++"
#define CXXFLAGS "--std=c++0x -D_GNU_SOURCE -fno-omit-frame-pointer -fpermissive -march=native -O3 -g -flto"
#define OPTIMIZE "-O3"
