#define INCL_STDLIB_H
#define INCL_UNISTD_H
#define INCL_TIME_H
#define USE_TZSET
#define INCL_SYS_TIMES_H
#define INCL_FCNTL_H
#define INCL_SYS_TIME_H
#define INCL_LIMITS_H
#define INCL_INTTYPES_H
#define INCL_STDINT_H
#define INCL_FLOAT_H
#define INCL_LOCALE_H
#define INCL_NETINET_IN_H
#define INCL_ARPA_INET_H
#define INCL_SYS_TYPES_H
#define INCL_SYS_IOCTL_H
#define INCL_SYS_SOCKET_H
#define INCL_NETDB_H
#define INCL_ARPA_TELNET_H
#define INCL_SYS_SOCKETVAR_H
#define INCL_SYS_STAT_H
#define INCL_DIRENT_H
#define USE_STRUCT_DIRENT
#define INCL_SYS_RESOURCE_H
#define INCL_SYS_WAIT_H
#define INCL_CRYPT_H
#define INCL_ALLOCA_H
#define INCL_EXECINFO_H
#define INCL_SYS_SYSMACROS_H
#define INCL_DLFCN_H
#define DRAND48
#define USE_BSD_SIGNALS
#define SIGNAL_ERROR SIG_ERR
#define CONST const
#define HAS_STRERROR
#define HAS_GETCWD
#define RUSAGE
#define HAS_GETTIMEOFDAY
#define SIZEOF_INT 4
#define SIZEOF_PTR 4
#define SIZEOF_SHORT 2
#define SIZEOF_FLOAT 8
#define SIZEOF_LONG 4
#define SIZEOF_LONGLONG 8
#define SIZEOF_LPC_INT 8
#define SIZEOF_LPC_FLOAT 8
#define UINT32 unsigned long
#define INCL_MYSQL_MYSQL_H
#define CONFIGURE_VERSION   5

