{
  "__SAVE_EXTENSION__", " \".o\"",
  "__RECEIVE_SNOOP__", " ",
  "__APPLY_CACHE_BITS__", " 11",
  "__DEFAULT_PRAGMAS__", " PRAGMA_WARNINGS + PRAGMA_STRICT_TYPES",
  "__DEBUGMALLOC_EXTENSIONS__", " ",
  "__DEBUGMALLOC__", " ",
  "__COMPILER_STACK_SIZE__", " 200	",
  "__SMALL_STRING_SIZE__", "     100",
  "__NO_LIGHT__", " ",
  "__LARGEST_PRINTABLE_STRING__", " 8192",
  "__BINARIES__", " ",
  "__MAX_TRACE__", " 30		",
  "__MAX_LOCAL__", " 25		",
  "___OPTIONS_H___", " ",
  "__LARGE_STRING_SIZE__", "     1000",
  "__NEXT_MALLOC_DEBUG__", " ",
  "__LIVING_HASH_SIZE__", " 256	",
  "__HEARTBEAT_INTERVAL__", " 2000000",
  "__NO_ANSI__", " ",
  "__EVALUATOR_STACK_SIZE__", " 1000	",
  "__NONINTERACTIVE_STDERR_WRITE__", " ",
  "__RESTRICTED_ED__", " ",
  "__NEW_FUNCTIONS__", " ",
  "__MATH__", " ",
  "__ARGUMENTS_IN_TRACEBACK__", " ",
  "__MAX_USERS__", " 50	        ",
  "__MAX_SAVE_SVALUE_DEPTH__", " 25",
  "__AUTO_TRUST_BACKBONE__", " ",
  "__SOCKET_EFUNS__", " ",
  "__MAX_EFUN_SOCKS__", " 16	",
  "__OPTIMIZE_FUNCTION_TABLE_SEARCH__", " ",
  "__TRAP_CRASHES__", " ",
  "__COMMAND_BUF_SIZE__", "      2000",
  "__NO_MUDLIB_STATS__", " ",
  "__CONFIG_FILE_DIR__", " \"/usr/local/mud/mudos/etc\"",
  "__MESSAGE_BUFFER_SIZE__", " 4096",
  "__CACHE_STATS__", " ",
};

#define NUM_OPTION_DEFS 37

