# Find PCRE2 (8-bit), the library FluffOS's pcre package links.
#
# PCRE_INCLUDE_DIRS - where to find pcre2.h
# PCRE_LIBRARIES    - libpcre2-8
# PCRE_FOUND        - True if PCRE2 was found.

FIND_PATH(PCRE_INCLUDE_DIR NAMES pcre2.h)
FIND_LIBRARY(PCRE_LIBRARY NAMES pcre2-8)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRE DEFAULT_MSG PCRE_LIBRARY PCRE_INCLUDE_DIR)

IF(PCRE_FOUND)
    SET(PCRE_LIBRARIES ${PCRE_LIBRARY})
    SET(PCRE_INCLUDE_DIRS ${PCRE_INCLUDE_DIR})
ELSE(PCRE_FOUND)
    SET(PCRE_LIBRARIES)
    SET(PCRE_INCLUDE_DIRS)
ENDIF(PCRE_FOUND)

MARK_AS_ADVANCED(PCRE_INCLUDE_DIRS PCRE_LIBRARIES)
