.\"find a player by name
.TH find_player 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
find_player() - find a player by name

.SH SYNOPSIS
object find_player( string str );

.SH DESCRIPTION
Similar to find_living(), but only searches through objects that are
interactive, or were once interactive.

.SH SEE ALSO
lower_case(3), find_living(3), livings(3), users(3), set_living_name(3)
