.\"determine if a player is in the editor
.TH in_edit 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
in_edit() - determine if a player is in the editor
 
.SH SYNOPSIS
int in_edit( object default : F_THIS_OBJECT );
 
.SH DESCRIPTION
Returns 1 if the given object is in the editor.
 
.SH SEE ALSO
ed(3), in_input(3)
