.\"determines if a player is inputting to an input_to
.TH in_input 3
 
.SH NAME
in_input() - determines if a player is inputting to an input_to
 
.SH SYNOPSIS
int in_input(object default : F_THIS_OBJECT);
 
.SH DESCRIPTION
Returns 1 if the object is currently inputting to an input_to.
 
.SH SEE ALSO
input_to(3)
