.\"determines if a player is inputting to an input_to
.TH in_input 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
in_input() - determines if a player is inputting to an input_to
 
.SH SYNOPSIS
int in_input( object default : F_THIS_OBJECT );
 
.SH DESCRIPTION
Returns 1 if the object is currently inputting to an input_to or get_char.
 
.SH SEE ALSO
get_char(3), input_to(3)
