.\"detects whether or not a given object is an interactive
.TH interactive 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
interactive() - detects whether or not a given object is an interactive

.SH SYNOPSIS
int interactive( object ob );

.SH DESCRIPTION
Return non-zero if `ob' is an interactive player. 0 will be returned
if he is link dead.

.SH SEE ALSO
query_ip_number(3), query_ip_name(3), enable_commands(3)
