.\"determine how many seconds an interactive player has been idle
.TH query_idle 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_idle() - determine how many seconds an interactive player has been idle

.SH SYNOPSIS
int query_idle( object ob );

.SH DESCRIPTION
Query how many seconds a player object (ob) has been idling.

.SH SEE ALSO
in_edit(3), in_input(3)
