.\"determine how many seconds an interactive player has been idle
.TH query_idle 3

.SH NAME
query_idle() - determine how many seconds an interactive player has been idle

.SH SYNOPSIS
int query_idle(object ob);

.SH DESCRIPTION
Query how many seconds idle a player object (ob) has been.

.SH SEE ALSO
query_ed(3)
