.\"changes which object is the current player
.TH set_this_player 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH SYNOPSIS
void set_this_player( object who );

.SH DESCRIPTION
set_this_player() causes 'who' to become the new value of
this_player().  This efun is only available with __NO_ADD_ACTION__
defined, and is included since with __NO_ADD_ACTION__ parsing and
dispatching of commands is the mudlib's responsibility.

who can also be zero, in which this_player() is set to zero.

.SH SEE ALSO
this_player(3)
