.\"sends a message to all living objects
.TH shout 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
shout() - sends a message to all living objects

.SH SYNOPSIS
void shout( string str );

.SH DESCRIPTION
Sends the string `str' to all living objects except this_player().

.SH SEE ALSO
message(3), write(3), tell_object(3), tell_room(3), say(3)
