.\"snoop an interactive user
.TH snoop 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
snoop() - snoop an interactive user

.SH SYNOPSIS
varargs object snoop( object snooper, object snoopee );

.SH DESCRIPTION
When both arguments are used, begins snooping of `snoopee' by `snooper'.
If the second argument is omitted, turns off all snooping by `snoopee'.
Security for snoop() is normally controlled by a simul_efun.  snoop() returns
`snoopee' if successful in the two-argument case, and `snooper' if it was
successful in the single-argument case.  A return of 0 indicates failure.

.SH SEE ALSO
query_snoop(3), query_snooping(3)
