.\"determine if a given object was once interactive
.TH userp 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
userp() - determine if a given object was once interactive

.SH SYNOPSIS
int userp( object );

.SH DESCRIPTION
Returns 1 if the arg was once interactive.

.SH SEE ALSO
interactive(3), users(3), living(3)
