.\"return an array of objects containing all interactive players
.TH users 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
users() - return an array of objects containing all interactive players

.SH SYNOPSIS
object *users( void );

.SH DESCRIPTION
Return an array of objects, containing all interactive players.

.SH SEE ALSO
livings(3), children(3), objects(3)
