.\"determine if a player is in the editor
.TH in_edit 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
in_edit() - determine if a player is in the editor
 
.SH SYNOPSIS
string in_edit( object default : F_THIS_OBJECT );
 
.SH DESCRIPTION
If the given object is in the editor, the file being edited is
returned, else zero.
 
.SH SEE ALSO
ed(3), in_input(3)
