.\"return the interactive object than an interactive object is snooping
.TH query_snooping 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_snooping() - return the object than an object is snooping

.SH SYNOPSIS
object query_snooping( object ob );

.SH DESCRIPTION
If `ob' (an interactive object) is snooping another interactive object, the
snooped object is returned.  Otherwise, 0 is returned.

.SH SEE ALSO
snoop(3), query_snoop(3)
