.\"get IP name for player
.TH query_ip_name 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_ip_name() - return the ip name of a given player object.

.SH SYNOPSIS
string query_ip_name( object ob );

.SH DESCRIPTION
Return the IP address for player `ob'.  An asynchronous process `addr_server'
is used to find out these name in parallel.  If there are any failures to
find the ip-name, then the ip-number is returned instead.

.SH SEE ALSO
query_ip_number(3), query_host_name(3), resolve(3), socket_address(3)
