.\"return the snooper of an interactive object
.TH query_snoop 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
query_snoop() - return the snooper of an interactive object

.SH SYNOPSIS
object query_snoop( object ob );

.SH DESCRIPTION
If `ob' (an interactive object) is being snooped by another interactive object,
the snooping object is returned.  Otherwise, 0 is returned.

.SH SEE ALSO
snoop(3), query_snooping(3)
