.\"send a message to all users in the same environment as the sayer
.TH say 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
say() - send a message to all users in the same environment

.SH SYNOPSIS
varargs void say( string str, object obj );

.SH DESCRIPTION
Sends a message to the environment of the originator, all items in the
same environment, and all items inside of the originator.  The originator
is this_player(), unless this_player() == 0, in which case, the originator
is this_object().
.PP
The second argument is optional.  If second argument `obj' is specified,
the message is sent to all except `obj'.  If `obj' is not an object, but
an array of objects, all those objects are excluded from receiving the
message.

.SH SEE ALSO
message(3), write(3), shout(3), tell_object(3), tell_room(3)
