.\"determine whether or not a given variable is null.
.TH nullp 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
nullp() - determine whether or not a given variable is null.

.SH SYNOPSIS
int nullp( mixed arg );

.SH DESCRIPTION
Return 1 if `arg' is null.  'arg' will be null in the following
cases:
.TP
1.
it has not yet been initialized.
.TP
2.
it points to a destructed object.
.TP
3.
it is a function (formal) parameter that corresponds to a missing actual
argument.

.SH SEE ALSO
mapp(3), stringp(3), pointerp(3), objectp(3), intp(3),
bufferp(3), floatp(3), functionp(3), undefinedp(3), errorp(3)
