#pragma once

// Custom opcodes that are not generated by efuns.autogen.h yet.
#ifndef F_NULLISH
#define F_NULLISH 230  // Nullish coalescing operator ??
#endif

#ifndef F_LOR_EQ
#define F_LOR_EQ 231  // Logical-or assignment (||=)
#endif

#ifndef F_LAND_EQ
#define F_LAND_EQ 232  // Logical-and assignment (&&=)
#endif

#ifndef F_NULLISH_EQ
#define F_NULLISH_EQ 233  // Nullish assignment (??=)
#endif

#ifndef F_ASSIGN_VALUE
#define F_ASSIGN_VALUE 234  // Assign with (value, lvalue) stack order
#endif
