.\"return the inventory of an object
.TH all_inventory 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
all_inventory() - return the inventory of an object

.SH SYNOPSIS
object *all_inventory( object ob );

.SH DESCRIPTION
Returns an array of the objects contained in the inventory of <ob>.

.SH SEE ALSO
first_inventory(3), next_inventory(3), deep_inventory(3)
