.\"return the nested inventory of an object
.TH deep_inventory 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
deep_inventory() - return the nested inventory of an object

.SH SYNOPSIS
object *deep_inventory( object ob );

.SH DESCRIPTION
Returns an array of the objects contained in the inventory of <ob> and
all the objects contained in the inventories of those objects and so on.

.SH SEE ALSO
first_inventory(3), next_inventory(3), all_inventory(3)
