.\"move current object to another environment
.TH move_object 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
move_object() - move current object to another environment
 
.SH SYNOPSIS
void move_object( object item, mixed dest );
 
.SH DESCRIPTION
Move the object `item' into the object `dest'.  'item' must be this_object().
move_object may be optionally called with one argument in which case 'item' 
is implicitly this_object() and the passed argument is 'dest'.
 
.SH SEE ALSO
this_object(3), move(4)
