.\"load a copy of an object
.TH new 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
new() - load a copy of an object

.SH SYNOPSIS
object new( string name );

.SH DESCRIPTION
Load a new object from definition <name>, and give it a new unique
name.  Returns the new object.  An object with a nonzero environment()
cannot be cloned.

.SH SEE ALSO
clone_object(3), destruct(3), move_object(3)
