.\"return the next object in the same inventory as the specified object
.TH next_inventory 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
next_inventory() - return the next object in the same inventory

.SH SYNOPSIS
object next_inventory( object ob );

.SH DESCRIPTION
Return the next object in the same inventory as `ob'.
.PP
Warning: If the object `ob' is moved by "move_object()",
then "next_inventory()" will return an object from the new inventory.

.SH SEE ALSO
first_inventory(3), all_inventory(3), deep_inventory(3)
