.\"return an object to its just-loaded state
.TH reload_object 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
reload_object - return an object to its just-loaded state
 
.SH SYNOPSIS
void reload_object( object ob );
 
.SH DESCRIPTION
When reload_object() is called on `ob', all the driver-maintained properties
are re-initialized (heart_beat, call_outs, light, shadows, etc), all 
variables are re-initialized, and create() is called.  It has a similar
effect to destructing/reloading the object, however, no disk access or
parsing is performed.

.SH SEE ALSO
export_uid(3), new(3), clone_object(3), destruct(3)
