.\"get an object for a new user
.TH connect 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
connect - get an object for a new user

.SH SYNOPSIS
object connect( void );

.SH DESCRIPTION

The driver calls connect() in the master object whenever a new user logs
into the driver.  The object returned by connect() is used as the initial
user object.  Note that it is possible to use exec(3) to switch the user
connection from the initial user object to some other object.

.SH SEE ALSO
exec(3), logon(4)
