.\"resolve relative path name
.TH make_path_absolute 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
make_path_absolute - resolve relative path name

.SH SYNOPSIS
.nf
string make_path_absolute( string rel_path );

.SH DESCRIPTION
This master apply is called by the ed() efun to
resolves relative path names of a file to read/write, to an absolute path
name.

.SH SEE ALSO
ed(3)
