.\"controls whether or not an object can save its loaded program
.TH valid_save_binary 4 "5 Sep 1994" MudOS "Driver Applies"

.SH NAME
valid_save_binary - controls whether or not an object can save its program

.SH SYNOPSIS
int valid_save_binary( string file );

.SH DESCRIPTION
When the driver is compiled with ALWAYS_SAVE_BINARIES, or an object uses
'#pragma save_binary', valid_save_binary is called with the program's filename.
If valid_save_binary returns 1, the save will be allowed, otherwise it will
not.
