.\"controls whether or not a LPC->C compiled object can use asm { }
.TH valid_asm 4 "18 Sep 1994" MudOS "Driver Applies"

.SH NAME
valid_asm - controls whether or not a LPC->C compiled object can use asm { }

.SH SYNOPSIS
int valid_asm( string file );

.SH DESCRIPTION
When the driver is compiled with LPC_TO_C, valid_asm() is called whenever
the asm { } structure is found in code.  If it returns 0, the compilation
will terminate with an error.
.PP
The asm { } structure is used as follows:
.IP
.nf
asm {
  <C code>
}
.fi
.PP
It causes the code between the braces to be literally inserted into the
compiled file.

.SH SEE ALSO
valid_compile_to_c(4)
