.\"allocate a buffer
.TH allocate_buffer 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
allocate_buffer() - allocate a buffer
 
.SH SYNOPSIS
buffer allocate_buffer( int size );
 
.SH DESCRIPTION
Allocate a buffer of <size> elements.  The number of elements must be >= 0 
and not bigger than a system maximum (usually ~10000).  All elements are 
initialized to 0.
 
.SH SEE ALSO
bufferp(3), read_buffer(3), write_buffer(3), sizeof(3), to_int(3)

.SH AUTHOR
Truilkan
