.\"read from a file and return a buffer, or return part of a buffer as a string
.TH read_buffer 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
read_buffer() - read from a file and return a buffer, or return part of a buffer as a string
 
.SH SYNOPSIS
.nf
string | buffer read_buffer( string | buffer src,
                             int start,  int len );
 
.SH DESCRIPTION
If `src' is a string (filename), then the filename will be read, starting
at byte # `start', for `len' bytes, and returned as a buffer.  If neither
argument is given, the entire file is read.
 
If `src' is a buffer, then characters are read from the buffer beginning
at byte # `start' in the buffer, and for `len' # of bytes, and returned
as a string.
 
Note that the maximum number of bytes you can read from a file and into
a buffer is controlled via the 'maximum byte transfer' parameter in the
runtime config file.
 
.SH SEE ALSO
write_buffer(3), allocate_buffer(3), bufferp(3), read_bytes(3), write_bytes(3)
 
.SH AUTHOR
Truilkan
