.\"write a buffer to a file, or read into a buffer from a source
.TH write_buffer 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
write_buffer() - write a buffer to a file, or read into a buffer from a source
 
.SH SYNOPSIS
.nf
int write_buffer( string | buffer dest, int start,
                  mixed source );
 
.SH DESCRIPTION
If `dest' is a file, then `source' must be an int (and will be written to
the file in network-byte-order), a buffer, or a string, and `source' will
be written to the file `dest' starting at byte # `start'.
 
If `dest' is a buffer, then `source' will be written into the buffer starting
at byte # `start' in the buffer.  If `source' is an int, it will be written
in network-byte-order.
 
.SH SEE ALSO
read_buffer(3), allocate_buffer(3)

.SH AUTHOR
Truilkan
