name: CI on Windows

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [64]
        build: ["Debug", "RelWithDebInfo"]

    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
      - uses: actions/checkout@v4
      - name: Install
        run: |
          if [ "$MSYSTEM" = "MINGW32" ]; then
            echo "TODO"
          else
            pacman --noconfirm -S --needed mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-zlib mingw-w64-x86_64-pcre mingw-w64-x86_64-icu mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-jemalloc mingw-w64-x86_64-gtest
          fi
          pacman --noconfirm -S --needed bison make
      - name: Build
        run: |
          mkdir build && cd build && cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DMARCH_NATIVE=OFF -DPACKAGE_CRYPTO=OFF -DPACKAGE_DB_MYSQL="" -DPACKAGE_DB_SQLITE=1 .. && VERBOSE=1 make -j 2 install
      - name: run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: cd build && make test
      - name: Testsuite
        run: |
          cd testsuite && ../build/bin/driver etc/config.test -ftest
