.\"get pending call_out() information
.TH call_out_info 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
call_out_info() - get pending call_out() information

.SH SYNOPSIS
mixed *call_out_info( void );

.SH DESCRIPTION
Get information about all pending call outs. An array is returned,
where every item in the array consists 4 elements: the object,
the function, the delay to go, and the optional argument.

.SH SEE ALSO
call_out(3), remove_call_out(3)
