.\"execute a command as if given by the object
.TH command 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
command() - execute a command as if given by the object

.SH SYNOPSIS
int command( string str, object ob );

.SH DESCRIPTION
Execute `str' for object `ob', or this_object() if `ob' is omitted.  Note that
the usability of the second argument is determined by the local administrator
and will usually not be available, in which case an error will result.
In case of failure, 0 is returned, otherwise a numeric value is returned,
which is the LPC "evaluation cost" of the command.  Bigger numbers mean
higher cost, but the whole scale is subjective and unreliable.

.SH SEE ALSO
add_action(3), enable_commands(3)
