.\"encrypt a string
.TH crypt 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
crypt() - encrypt a string

.SH SYNOPSIS
string crypt( string str, string seed );

.SH DESCRIPTION
Crypt the string <str> using the first two characters from <seed> as
a seed. If <seed> is 0, then random seed is used.
.PP
The result has the first two characters as the seed.
