.\"return a time string
.TH ctime 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
ctime() - return a time string

.SH SYNOPSIS
string ctime( int clock );

.SH DESCRIPTION
Gives a nice string with current date and time, with the argument 'clock'
that is the number of seconds since 1970.

.SH SEE ALSO
time(3), time_expression(3), localtime(3), uptime(3)
