.\"generate a run-time error
.TH error 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
error - generate a run-time error
 
.SH SYNOPSIS
void error( string err );
 
.SH DESCRIPTION
A run-time error `err' will be generated when error() is called.  Execution
of the current thread will halt, and the trace will be recorded to the
debug log.
 
.SH SEE ALSO
catch(3), throw(3), error_handler(4)
