.\"find first call_out due to be executed for a given function
.TH find_call_out "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
find_call_out() - find a call out scheduled to be called next

.SH SYNOPSIS
int find_call_out( string func ):

.SH DESCRIPTION
Find the first call out due to be executed for function `func', and
return the time left. If it is not found, then return -1.

.SH SEE ALSO
call_out(3), remove_call_out(3), set_heart_beat(3)
