.\"get function profiling information for an object
.TH function_profile 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
function_profile() - get function profiling information for an object
 
.SH SYNOPSIS
mixed *function_profile( object ob );
 
.SH DESCRIPTION
Returns function profiling information for `ob', or this_object() if `ob'
is not specified.  This is only available if the driver was compiled
with PROFILE_FUNCTIONS defined.  
 
.SH RETURN VALUE
An array of mappings is returned, one for each function in `ob', the format 
of the mapping is:
.nf
       ([ "name"     : name_of_the_function,
          "calls"    : number_of_calls,

          /* cpu time expressed in microseconds */
          "self"     : cpu_time_spent_in self,
          "children" : cpu_time_spent_in_children
       ])
.fi 
The usefulness of this is tied to the resolution of the CPU clock--even 
though the units are microseconds, the CPU timer resolution is often much 
less
 
.SH SEE ALSO
rusage(3), time_expression(3), opcprof(3)
