.\"set the default error message to a specified string
.TH notify_fail 3

.SH NAME
void notify_fail(string str);

.SH DESCRIPTION
Store `str' as the error message to be returned instead of the default message
`What ?'.  The message will be displayed if a 0 is returned from an action
setup via add_action().  This is the preferred way to display error messages
since it allows other objects a chance to respond to the same verb (command).
Do not use write() to display the error message since this will require you
to return a 1 (unless you want to see the result of the write() in addition to
the 'what?' message).  However, if you do return a 1, then no other objects
will get a chance to respond to the user command.
.PP
If "notify_fail()" is called more than once, only the last call will have
an affect.
.PP
The idea behind this function is to allow better error messages than
`What ?'.
