.\"determine whether or not a given object is shadowing another
.TH shadowp3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
shadowp() - determine whether or not a given object it shadowing another

.SH SYNOPSIS
object shadowp( object ob );

.SH DESCRIPTION
Returns the object that `ob' is shadowing, or zero (0) if it is not
shadowing any object.

.SH SEE ALSO
shadow(3), objectp(3), query_shadowing(3), valid_shadow(4)
