.\"return a pseudo-random number
.TH random 3

.SH NAME
random() - return a pseudo-random number

.SH SYNOPSIS
int random(int n);

.SH DESCRIPTION
Return a pseudo-random number from the range [0 .. (n -1)] (inclusive).
The random number generator to be used is specified in the driver
port.h file when the driver is compiled.
