.\"reclaim any lingering objects
.TH reclaim_objects 3
 
.SH NAME
reclaim_objects - reclaim any lingering objets
 
.SH SYNOPSIS
int reclaim_objects();
 
.SH DESCRIPTION
Cycles through all objects that are loaded, and frees any lingering objects
that it can.  This could result in a sizable amount of memory being freed up,
depending on how the mud is coded.  Objects are typically left lingering
when a global variable in more than one object contains a pointer to it,
and the object gets destructed.
 
.SH SEE ALSO
destruct(3)
