.\"modify the time until reset on an object
.TH set_reset 3 "5 Sep 1994" MudOS "LPC Library Functions"
 
.SH NAME
set_reset - modify the time until reset on an object
 
.SH SYNOPSIS
varargs void set_reset( object ob, int time );
 
.SH DESCRIPTION
Sets the time until reset on `ob' to `time' seconds from now.  If `time'
is omitted, the driver's normal reset time setting formula is applied
to `ob', that is,
.PP
reset time = current_time + reset_time / 2 + random(reset_time / 2)
 
.SH SEE ALSO
reset(4)
