.\"return the time elapsed since the last driver reboot.
.TH uptime 3 "5 Sep 1994" MudOS "LPC Library Functions"

.SH NAME
uptime() - return the number of seconds elapsed since the last driver reboot

.SH SYNOPSIS
int uptime( void );

.SH DESCRIPTION
This function returns the number of seconds since the last driver reboot.

.SH SEE ALSO
time(3), ctime(3), localtime(3), time_expression(3)
