#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

TOP_SRCDIR=${1}
shift

ALL_OPTIONS_H=${TOP_SRCDIR}/src/base/internal/options_incl.h

PACKAGES_SPEC=packages.spec
PACKAGES_SPEC_FULL=packages.fullspec

# do pre-cleanup
rm -f "$PACKAGES_SPEC" "PACKAGES_SPEC_FULL" >/dev/null 2>&1 || true

PACKAGES=$("$@" -E -undef -dM $ALL_OPTIONS_H | grep PACKAGE_ | cut -d " " -f 2)

for P in $PACKAGES; do
	# get the package name, in uppercase
	P=${P#PACKAGE_} 
	# get the directory and file name
	DIR=$(echo $P | tr '[:upper:]' '[:lower:]')

	if [[ -e "${TOP_SRCDIR}/src/packages/$DIR/$DIR.spec" ]]; then
		echo "#include \"${TOP_SRCDIR}/src/packages/$DIR/$DIR.spec\"" >> $PACKAGES_SPEC
	else
		echo "Warning: ${TOP_SRCDIR}/src/packages/$DIR/$DIR.spec is missing."
	fi
done

"$@" -E -imacros $ALL_OPTIONS_H -P -x c++ $PACKAGES_SPEC > $PACKAGES_SPEC_FULL

# ---------------------------------------------------------------------------
# The efuns this build does NOT have, and which package each would come from.
#
# Packages are selected at compile time, so a driver built without one simply
# has no such efun and the compiler reports a bare "Undefined function hash"
# -- which says nothing about `hash` being a real efun that merely was not
# compiled in (issue #1352, where that cost a user a version bisect). The
# table below lets the diagnostic name the package instead.
#
# Only DISABLED packages are listed, and only names no ENABLED package also
# declares: ten efuns appear in two spec files (roll_MdN in both contrib and
# dwlib, filter/map/find_object in core and ops, ...), so "in a disabled
# package's spec" alone does not mean this driver lacks it. Listing one of
# those would attach "not built with PACKAGE_DWLIB" to an ordinary typo.
# ---------------------------------------------------------------------------
MISSING_EFUNS_H=packages_missing_efuns.autogen.h

# Efun names declared in one .spec file. A spec with none is not an error,
# hence the "|| true": the script runs under `set -e`/`pipefail`.
spec_efun_names() {
	sed -e 's://.*::' "$1" \
	  | grep -oE '^[A-Za-z_][A-Za-z0-9_ \t*|]*[ \t*]([A-Za-z_][A-Za-z0-9_]*)[ \t]*\(' \
	  | grep -oE '[A-Za-z_][A-Za-z0-9_]*[ \t]*\($' \
	  | sed -e 's:[ \t]*($::' \
	  | sort -u || true
}

PRESENT_EFUNS=$(
	for P in $PACKAGES; do
		D=$(echo "${P#PACKAGE_}" | tr '[:upper:]' '[:lower:]')
		if [[ -e "${TOP_SRCDIR}/src/packages/$D/$D.spec" ]]; then
			spec_efun_names "${TOP_SRCDIR}/src/packages/$D/$D.spec"
		fi
	done | sort -u
)

{
  echo "/* Generated by tools/build_packages_genfiles.sh -- do not edit."
  echo " * Efun name -> the package it needs, for packages NOT built into this"
  echo " * driver. Consulted only when a name is already known not to resolve."
  echo " * Terminated by a {nullptr, nullptr} sentinel, which is also all there"
  echo " * is when every package is enabled."
  echo " */"
  echo "#ifndef PACKAGES_MISSING_EFUNS_AUTOGEN_H"
  echo "#define PACKAGES_MISSING_EFUNS_AUTOGEN_H"
  echo ""
  echo "struct missing_efun_t {"
  echo "  const char *name;    /* the efun's name */"
  echo "  const char *package; /* the PACKAGE_* option that would provide it */"
  echo "};"
  echo ""
  echo "static const missing_efun_t missing_efuns[] = {"
} > "$MISSING_EFUNS_H"

for SPEC in "${TOP_SRCDIR}"/src/packages/*/*.spec; do
	DIR=$(basename "$(dirname "$SPEC")")
	PKG="PACKAGE_$(echo "$DIR" | tr '[:lower:]' '[:upper:]')"
	if echo "$PACKAGES" | grep -qx "$PKG"; then
		continue  # this build has it
	fi
	while read -r EFUN; do
		[[ -n "$EFUN" ]] || continue
		if echo "$PRESENT_EFUNS" | grep -qx "$EFUN"; then
			continue  # an enabled package declares it too
		fi
		echo "    {\"$EFUN\", \"$PKG\"}," >> "$MISSING_EFUNS_H"
	done < <(spec_efun_names "$SPEC")
done

{
  echo "    {nullptr, nullptr},"
  echo "};"
  echo ""
  echo "#endif /* PACKAGES_MISSING_EFUNS_AUTOGEN_H */"
} >> "$MISSING_EFUNS_H"