/*
 * build_applies.cc , Original from edit_source.cc
 *
 * This tool parse "applies" list and generate applies_table.cc/applies_table.h.
 */

#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <cctype>

static const char *APPLIES = "vm/internal/applies";
static const char *APPLIES_H = "vm/internal/applies_table.autogen.h";
static const char *APPLIES_TABLE = "vm/internal/applies_table.autogen.cc";

int main() {
  FILE *f = fopen(APPLIES, "r");
  FILE *out = fopen(APPLIES_H, "w");
  FILE *table = fopen(APPLIES_TABLE, "w");
  char buf[8192];
  char *colon;
  char *p;
  int apply_number = 0;

  fprintf(out,
          "/* autogenerated from 'applies' */\n#ifndef APPLIES_H\n#define "
          "APPLIES_H\n\nextern const char *applies_table[];\n\n/* the folowing "
          "must be the first character of __INIT */\n#define "
          "APPLY___INIT_SPECIAL_CHAR\t\t'#'\n");
  fprintf(table,
          "/* autogenerated from 'applies' */\n\nconst char *applies_table[] = "
          "{\n");

  while (fgets(buf, 8192, f)) {
    buf[strlen(buf) - 1] = 0;
    if (buf[0] == '#') {
      break;
    }
    if ((colon = strchr(buf, ':'))) {
      *colon++ = 0;
      fprintf(out, "#define APPLY_%-30s\t\"%s\"\n", buf, colon);
    } else {
      fprintf(out, "#define APPLY_%-30s\t", buf);
      p = buf;
      while (*p) {
        *p = tolower(*p);
        p++;
      }
      fprintf(out, "\"%s\"\n", buf);
    }
  }
  while (fgets(buf, 8192, f)) {
    buf[strlen(buf) - 1] = 0;
    if ((colon = strchr(buf, ':'))) {
      *colon++ = 0;
      fprintf(table, "\t\"%s\",\n", colon);
      fprintf(out, "#define APPLY_%-30s\t%i\n", buf, apply_number++);
    } else {
      fprintf(out, "#define APPLY_%-30s\t%i\n", buf, apply_number++);
      p = buf;
      while (*p) {
        *p = tolower(*p);
        p++;
      }
      fprintf(table, "\t\"%s\",\n", buf);
    }
  }

  fprintf(table, "};\n");
  fprintf(out, "\n#define NUM_MASTER_APPLIES\t%i\n\n#endif\n", apply_number);

  fclose(out);
  fclose(table);
  fclose(f);

  return 0;
}
